### ISSUE TITLE
Allow custom JSON responses by using *js files and URL Parameters

### ISSUE THREAD

**Issue by hputzek** [diva-e/servemocks#2]
Would be nice to allow creating custom JSON responses that can react on URL Query Parameters.

Example:
 
`/api/cars?resultCount=10`
 
In the folder structure there is a file `/api/cars.mjs` 
This file export default a function with awaits `req.query" as a parameter and therefore can react to url query params.
It must return an `object` which can then be converted to JSON and be returned as a result.

**Comment by anoack93** [comment]
@hputzek I'm currently working on a v2 of servemocks which will be based on es modules. Support for old versions of node will be dropped and I decided to implement the feature you have mentioned here based on a former MR which you have created

https://github.com/diva-e/servemocks/pull/10/commits/2174f9ec333a9b2f7591985837da9e06a7d148a6

I'm still testing this in a project.

**Comment by anoack93** [comment]
this is part of the 2.0.0 release
